services:
  db:
    container_name: mysql8
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password --collation-server=utf8_general_ci --character-set-server=utf8 --sql_mode="" --skip-log-bin
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: 'laravel'
    ports:
      - '3307:3306'
    networks:
      - wpsite

  phpmyadmin:
    container_name: pma
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - '9090:80'
    environment:
      PMA_ABSOLUTE_URI: http://pma
      PMA_HOSTS: db
      MYSQL_ROOT_PASSWORD: root
      PMA_PASSWORD: root
      PMA_USER: root
    networks:
      - wpsite

  php8.3:
    container_name: php8.3
    depends_on:
      - db
    build:
      context: ./docker/php8.3
    restart: always
    ports:
      - "9900:9000"
    volumes:
      - ./:/project/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - wpsite

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./:/project/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - wpsite


networks:
  wpsite:
    driver: bridge
